// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvVwRhssErWm7JrvjUrf3vyJ71o9L8GXE',
    appId: '1:352328487562:web:b7b50f6900b25483835373',
    messagingSenderId: '352328487562',
    projectId: 'flutterproject-1f622',
    authDomain: 'flutterproject-1f622.firebaseapp.com',
    storageBucket: 'flutterproject-1f622.appspot.com',
    measurementId: 'G-SMKRL1432Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyrNDtTVgPNjkexuVT1ETzWOW2s2fZrNk',
    appId: '1:352328487562:android:a150c9251780cf40835373',
    messagingSenderId: '352328487562',
    projectId: 'flutterproject-1f622',
    storageBucket: 'flutterproject-1f622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEnsr-3VxWeZ4h65pL89zMEQzRUm7JLck',
    appId: '1:352328487562:ios:5e1d1fbbc050800c835373',
    messagingSenderId: '352328487562',
    projectId: 'flutterproject-1f622',
    storageBucket: 'flutterproject-1f622.appspot.com',
    iosClientId: '352328487562-t4ndf4flumofb7jfv26ddi8i0e6k09n4.apps.googleusercontent.com',
    iosBundleId: 'com.tuannguyen.myFirstFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEnsr-3VxWeZ4h65pL89zMEQzRUm7JLck',
    appId: '1:352328487562:ios:5e1d1fbbc050800c835373',
    messagingSenderId: '352328487562',
    projectId: 'flutterproject-1f622',
    storageBucket: 'flutterproject-1f622.appspot.com',
    iosClientId: '352328487562-t4ndf4flumofb7jfv26ddi8i0e6k09n4.apps.googleusercontent.com',
    iosBundleId: 'com.tuannguyen.myFirstFlutterProject',
  );
}
